### ISSUE TITLE
Change analysis options

### ISSUE THREAD

**Issue by alexeieleusis** [alexeieleusis/shuttlecock#30]
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  language:
    - enableGenericMethods: true
    - enableSuperMixins: true
```
